CREATE TABLE Clientes (
DNI VARCHAR(15) PRIMARY KEY,
Nombre VARCHAR(50),
Direccion VARCHAR(50)
) ENGINE=INNODB;

CREATE TABLE Pagos_Pendientes (
DNI VARCHAR(15),
Importe DOUBLE,
FOREIGN KEY (DNI) REFERENCES Clientes (DNI)
ON DELETE NO ACTION
ON UPDATE NO ACTION
) ENGINE=INNODB;

INSERT INTO Clientes
VALUES ('55555672L','Pepe Cifuentes','C/Los Almendros, 23');

INSERT INTO Pagos_Pendientes VALUES ('55555672L',500);

INSERT INTO Pagos_Pendientes VALUES ('55555672L',234.5);